{% set name = "stylegan2-pytorch" %}
{% set version = "1.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stylegan2_pytorch-{{ version }}.tar.gz
  sha256: 6c7f08082cec2b35717e5359f2e6c453449814777646414e19af810d29a88136

build:
  number: 0
  noarch: python
  entry_points:
    - stylegan2_pytorch = stylegan2_pytorch.cli:main

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - aim
    - contrastive-learner >=0.1.0
    - einops
    - fire
    - kornia >=0.5.4
    - numpy
    - pillow
    - python >=3.6
    - retry
    - pytorch
    - torchvision
    - tqdm
    - vector-quantize-pytorch ==0.1.0

test:
  imports:
    - stylegan2_pytorch
  commands:
    - pip check
    - stylegan2_pytorch --help
  requires:
    - pip


about:
  home: https://github.com/lucidrains/stylegan2-pytorch
  summary: StyleGan2 in Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
